- hosts: all
  tasks:
  - name: "configuring repo for docker"
    yum_repository:
            name: "docker"
            description: "yum for docker"
            baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
            gpgcheck: no

  - name: "installing docker"
    package:
            name: "docker-ce-18.06.3.ce-3.el7.x86_64"
            state: present
    register: docker_installed

  - name: "starting docker service"
    service: 
            name: "docker"
            state: started
            enabled: yes
    register: docker_started        

  - name: "creating a persistence volune dir in containter"
    file:
            path: "/root/mypv"
            state: directory
  - name: "copy the web files to the server dir mypv"
    copy:
            src: "/root/ansible_ws/home.html"
            dest: "/root/mypv"
  - name: "python installation"
    package:
            name: "python3"
            state: present

  - name: "installing docker SDK"
    command: "pip3 install docker-py"
    

  - name: "pull httpd image"
    docker_container:
           name: webserver
           image: httpd
           pull: yes
           state: started
           exposed_ports:
                   - "80"
           ports:
                   - 8080:80
           volumes:
                   - /root/mypv:/usr/local/apache2/htdocs  


